/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

// got help from: https://stackoverflow.com/questions/13185727/reading-a-txt-file-using-scanner-class-in-java

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Random;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    public static void main(String[] args) {
        File file = new File("src/main/resources/recentquotes.json");
        String jsonString = "";
        try {
            Scanner sc = new Scanner(file);
            while (sc.hasNextLine()){
                jsonString += sc.nextLine();
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        Gson gson = new Gson();

        Quotes[] words = gson.fromJson(jsonString, Quotes[].class);
        Random quoteGenerator = new Random();
        int random = quoteGenerator.nextInt(words.length);
        System.out.println(words[5]);

        //random quot generator


    }
}
